### ISSUE TITLE
Fix hyphenation for fee-waiver => fee waiver

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-MATCSmallClaims#115]
"If you cannot afford to pay the filing fee you can ask the court for a waiver. You can complete a fee-waiver form during this interview."

**Comment by nonprofittechy** [comment]
Even if technically correct, it looks very odd to me. "Fee waiver" is usually used alone, as the title of the form.

Maybe we can rewrite to avoid the unusual term? 

> If you cannot afford to pay the filing fee you can ask the court for a waiver. You can complete a fee-waiver form during this interview.

to 

> If you cannot afford to pay the filing fee you can ask the court for permission to file for free. This interview will help you ask the court.

**Comment by samglover** [comment]
It's technically correct, yes, but the reason to hyphenate a compound adjective is to help avoid ambiguity. A "fee-waiver petition" can only mean a petition for waiving the fee. A "fee waiver petition" could suggest a waiver petition that has a fee attached to it.

It's not a hill I intend to die on in this case. It's difficult for my brain to make sense of the second meaning, and clarity is after all the goal.

(Contrast "small firm website," which could mean a firm website that is small, with "small-firm website," which means the website of a small firm, no matter the size of the website. In that case I will always insist the hyphen is necessary.)

However, if we meant to use the proper title of the form then we should do that, including capitalization to indicate it is a title rather than just a description of a kind of form.

But in the end I prefer your suggested change so I'm going with it and I hope the court agrees.
